---
title: "R Notebook"
output: html_notebook
---


### Load dataset
```{r}
library(readr)
library(dplyr)
library(tidyr)

heart <- read_table("University of Michigan Dropbox/Xingran Chen/UMICH Courses/BIOSTAT 885/project/heart.txt")
heart <- heart %>%
  select(-tx.date, -birth.dt, -accept.dt, -fu.date, -futime)

heart <- heart %>%
  filter(age > 18)
heart$alive <- ifelse(heart$fustat == 0, 1, 0)

complete.heart <- heart[complete.cases(heart), ]

```

### Summary statistics


```{r}
heart %>%
  group_by(alive) %>%
  summarise(
    age.mean = mean(age, na.rm = TRUE),
    age.sd = sd(age, na.rm = TRUE),
  )

print("surgery")
table(heart$alive, heart$surgery)
print("transplant")
table(heart$alive, heart$transplant)
```

```{r}
pdf("/Users/chenxingran/University of Michigan Dropbox/Xingran Chen/UMICH Courses/BIOSTAT 885/age_hist.pdf", width = 8, height = 5)
hist(heart$age, xlab = "Age", main = "")
```

## Q1 if heart transplant may increase chance of survival

```{r}
summary(glm(alive ~ transplant, data = heart, family = binomial))
```

## Q2
### Logistic Regression
```{r fig.width=8, fig.height=5}
# fit a logistic regression model to predict fustat using transplant
q1.model.glm <- glm(alive ~ transplant * age, data = heart, family = binomial)
summary(q1.model.glm)

# plot probability curve of tranplant = 1 / 0 over age.
age.range <- seq(min(heart$age), max(heart$age), length.out = 100)
transplant.data <- data.frame(age = age.range, transplant = rep(1, 100))
notransplant.data <- data.frame(age = age.range, transplant = rep(0, 100))

tmp <- predict(q1.model.glm, newdata = transplant.data, type = "link", se.fit = TRUE)
glm.transplant.prob <- plogis(tmp$fit)
glm.transplant.ub <- plogis(tmp$fit + qnorm(0.975) * tmp$se.fit)
glm.transplant.lb <- plogis(tmp$fit - qnorm(0.975) * tmp$se.fit)

tmp <- predict(q1.model.glm, newdata = notransplant.data, type = "link", se.fit = TRUE)
glm.notransplant.prob <- plogis(tmp$fit)
glm.notransplant.ub <- plogis(tmp$fit + qnorm(0.975) * tmp$se.fit)
glm.notransplant.lb <- plogis(tmp$fit - qnorm(0.975) * tmp$se.fit)

pdf("/Users/chenxingran/University of Michigan Dropbox/Xingran Chen/UMICH Courses/BIOSTAT 885/glm.pdf", width = 8, height = 5)
plot(age.range, glm.transplant.prob, type = "l", xlab = "Age", 
     ylab = "Probability of Survival", ylim = c(0, 1), col = "blue", lwd = 2)
par(cex = 1.1,            
    cex.axis = 1.1,       
    cex.lab = 1.1,        
    cex.main = 1.1,      
    cex.sub = 1.1)

lines(age.range, glm.transplant.ub, col = "blue", lty=2, lwd=1)
lines(age.range, glm.transplant.lb, col = "blue", lty=2, lwd=1)
lines(age.range, glm.notransplant.prob, col = "red", lty=1, lwd=2)
lines(age.range, glm.notransplant.ub, col = "red", lty=2, lwd=1)
lines(age.range, glm.notransplant.lb, col = "red", lty=2, lwd=1)

legend("topright", legend=c("Transplant", "No Transplant"), col=c("blue", "red"), lty=1:2, cex=0.8)

```

### Kernel Regression with Uniform Kernel


```{r fig.width=8, fig.height=5}

h <- 15
ks.uniform.transplant.prob <- c()
ks.uniform.transplant.ub <- c()
ks.uniform.transplant.lb <- c()
ks.uniform.notransplant.prob <- c()
ks.uniform.notransplant.ub <- c()
ks.uniform.notransplant.lb <- c()
ordered.heart <- heart[order(heart$age), ]
for (i in 1:nrow(heart)){
  # select only the data points within the window
  subdata <- ordered.heart[ordered.heart$age >= ordered.heart$age[i] - h & ordered.heart$age <= ordered.heart$age[i] + h, ]
  subdata.model <- glm(factor(alive) ~ age * transplant, data=subdata, family=binomial(link="logit"))

  tmp <- predict(subdata.model, newdata=data.frame(age=ordered.heart$age[i], transplant=1), type="link", se.fit=TRUE)
  ks.uniform.transplant.prob <- c(ks.uniform.transplant.prob, plogis(tmp$fit))
  ks.uniform.transplant.ub <- c(ks.uniform.transplant.ub, plogis(tmp$fit + qnorm(0.975) * tmp$se.fit))
  ks.uniform.transplant.lb <- c(ks.uniform.transplant.lb, plogis(tmp$fit - qnorm(0.975) * tmp$se.fit))
  
  tmp <- predict(subdata.model, newdata=data.frame(age=ordered.heart$age[i], transplant=0), type="link", se.fit=TRUE)
  ks.uniform.notransplant.prob <- c(ks.uniform.notransplant.prob, plogis(tmp$fit))
  ks.uniform.notransplant.ub <- c(ks.uniform.notransplant.ub, plogis(tmp$fit + qnorm(0.975) * tmp$se.fit))
  ks.uniform.notransplant.lb <- c(ks.uniform.notransplant.lb, plogis(tmp$fit - qnorm(0.975) * tmp$se.fit))
}

pdf("/Users/chenxingran/University of Michigan Dropbox/Xingran Chen/UMICH Courses/BIOSTAT 885/ks_uniform.pdf", width = 8, height = 5)
plot(ordered.heart$age, ks.uniform.transplant.prob, type = "l", xlab = "Age", 
     ylab = "Probability of Survival", ylim = c(0, 1), col = "blue", lwd = 2)
par(cex = 1.1,            
    cex.axis = 1.1,       
    cex.lab = 1.1,        
    cex.main = 1.1,      
    cex.sub = 1.1)

lines(ordered.heart$age, ks.uniform.transplant.ub, col = "blue", lty=2, lwd=1)
lines(ordered.heart$age, ks.uniform.transplant.lb, col = "blue", lty=2, lwd=1)
lines(ordered.heart$age, ks.uniform.notransplant.prob, col = "red", lty=1, lwd=2)
lines(ordered.heart$age, ks.uniform.notransplant.ub, col = "red", lty=2, lwd=1)
lines(ordered.heart$age, ks.uniform.notransplant.lb, col = "red", lty=2, lwd=1)
legend("topright", legend=c("Transplant", "No Transplant"), col=c("blue", "red"), lty=1:2, cex=0.8)

```

### Kernel regression with Gaussian kernel
```{r fig.width=8, fig.height=5}
h <- 5
ks.gaussian.transplant.prob <- c()
ks.gaussian.transplant.ub <- c()
ks.gaussian.transplant.lb <- c()
ks.gaussian.notransplant.prob <- c()
ks.gaussian.notransplant.ub <- c()
ks.gaussian.notransplant.lb <- c()
ordered.heart <- heart[order(heart$age), ]
for (i in 1:nrow(heart)){
  gaussian_weights <- exp(-((ordered.heart$age - ordered.heart$age[i])^2) / (2 * h^2))
  subdata.model <- glm(alive ~ age * transplant, 
                       data=ordered.heart,
                       weights=gaussian_weights,
                       family=binomial(link="logit"))

  tmp <- predict(subdata.model, newdata=data.frame(age=ordered.heart$age[i], transplant=1), type="link", se.fit=TRUE)
  ks.gaussian.transplant.prob <- c(ks.gaussian.transplant.prob, plogis(tmp$fit))
  ks.gaussian.transplant.ub <- c(ks.gaussian.transplant.ub, plogis(tmp$fit + qnorm(0.975) * tmp$se.fit))
  ks.gaussian.transplant.lb <- c(ks.gaussian.transplant.lb, plogis(tmp$fit - qnorm(0.975) * tmp$se.fit))
  
  tmp <- predict(subdata.model, newdata=data.frame(age=ordered.heart$age[i], transplant=0), type="link", se.fit=TRUE)
  ks.gaussian.notransplant.prob <- c(ks.gaussian.notransplant.prob, plogis(tmp$fit))
  ks.gaussian.notransplant.ub <- c(ks.gaussian.notransplant.ub, plogis(tmp$fit + qnorm(0.975) * tmp$se.fit))
  ks.gaussian.notransplant.lb <- c(ks.gaussian.notransplant.lb, plogis(tmp$fit - qnorm(0.975) * tmp$se.fit))
}

pdf("/Users/chenxingran/University of Michigan Dropbox/Xingran Chen/UMICH Courses/BIOSTAT 885/ks_gaussian.pdf", width = 8, height = 5)
plot(ordered.heart$age, ks.gaussian.transplant.prob, type = "l", xlab = "Age",
     ylab = "Probability of Survival", ylim = c(0, 1), col = "blue", lwd = 2)
par(cex = 1.1,            
    cex.axis = 1.1,       
    cex.lab = 1.1,        
    cex.main = 1.1,      
    cex.sub = 1.1)

lines(ordered.heart$age, ks.gaussian.transplant.ub, col = "blue", lty=2, lwd=1)
lines(ordered.heart$age, ks.gaussian.transplant.lb, col = "blue", lty=2, lwd=1)
lines(ordered.heart$age, ks.gaussian.notransplant.prob, col = "red", lty=1, lwd=2)
lines(ordered.heart$age, ks.gaussian.notransplant.ub, col = "red", lty=2, lwd=1)
lines(ordered.heart$age, ks.gaussian.notransplant.lb, col = "red", lty=2, lwd=1)
legend("topright", legend=c("Transplant", "No Transplant"), col=c("blue", "red"), lty=1:2, cex=0.8)

```

### Kernel regression with Epanechnikov kernel
```{r fig.width=8, fig.height=5}
h <- 20
ks.epanechnikov.transplant.prob <- c()
ks.epanechnikov.transplant.ub <- c()
ks.epanechnikov.transplant.lb <- c()
ks.epanechnikov.notransplant.prob <- c()
ks.epanechnikov.notransplant.ub <- c()
ks.epanechnikov.notransplant.lb <- c()
ordered.heart <- heart[order(heart$age), ]
for (i in 1:nrow(heart)){
  diff <- (ordered.heart$age - ordered.heart$age[i]) / h
  epanechnikov_weights <- ifelse(abs(diff) <= 1, (3/4) * (1 - diff^2), 0)
  subdata.model <- glm(alive ~ age * transplant, 
                       data=ordered.heart,
                       weights=epanechnikov_weights,
                       family=binomial(link="logit"))

  tmp <- predict(subdata.model, newdata=data.frame(age=ordered.heart$age[i], transplant=1), type="link", se.fit=TRUE)
  ks.epanechnikov.transplant.prob <- c(ks.epanechnikov.transplant.prob, plogis(tmp$fit))
  ks.epanechnikov.transplant.ub <- c(ks.epanechnikov.transplant.ub, plogis(tmp$fit + qnorm(0.975) * tmp$se.fit))
  ks.epanechnikov.transplant.lb <- c(ks.epanechnikov.transplant.lb, plogis(tmp$fit - qnorm(0.975) * tmp$se.fit))
  
  tmp <- predict(subdata.model, newdata=data.frame(age=ordered.heart$age[i], transplant=0), type="link", se.fit=TRUE)
  ks.epanechnikov.notransplant.prob <- c(ks.epanechnikov.notransplant.prob, plogis(tmp$fit))
  ks.epanechnikov.notransplant.ub <- c(ks.epanechnikov.notransplant.ub, plogis(tmp$fit + qnorm(0.975) * tmp$se.fit))
  ks.epanechnikov.notransplant.lb <- c(ks.epanechnikov.notransplant.lb, plogis(tmp$fit - qnorm(0.975) * tmp$se.fit))
}

pdf("/Users/chenxingran/University of Michigan Dropbox/Xingran Chen/UMICH Courses/BIOSTAT 885/ks_epanechnikov.pdf", width = 8, height = 5)
par(cex = 1.1,            
    cex.axis = 1.1,       
    cex.lab = 1.1,        
    cex.main = 1.1,      
    cex.sub = 1.1)

plot(ordered.heart$age, ks.epanechnikov.transplant.prob, type = "l", xlab = "Age",
     ylab = "P0robability of Survival", ylim = c(0, 1), col = "blue", lwd = 2)
lines(ordered.heart$age, ks.epanechnikov.transplant.ub, col = "blue", lty=2, lwd=1)
lines(ordered.heart$age, ks.epanechnikov.transplant.lb, col = "blue", lty=2, lwd=1)
lines(ordered.heart$age, ks.epanechnikov.notransplant.prob, col = "red", lty=1, lwd=2)
lines(ordered.heart$age, ks.epanechnikov.notransplant.ub, col = "red", lty=2, lwd=1)
lines(ordered.heart$age, ks.epanechnikov.notransplant.lb, col = "red", lty=2, lwd=1)
legend("topright", legend=c("Transplant", "No Transplant"), col=c("blue", "red"), lty=1:2, cex=0.8)

```

### GAM
```{r fig.width=8, fig.height=5}
library(mgcv)

# gam.model <- gam(alive ~ s(age, k = 20, by = factor(transplant)) + factor(transplant), data = heart, family = binomial)
# for the above model, iterate k from 1 to 20, and select the best model based on AIC
for (k in 1:20){
  gam.model <- gam(alive ~ s(age, k = k, by = factor(transplant)) + factor(transplant), data = heart, family = binomial)
  print(paste("k = ", k, "AIC = ", AIC(gam.model), "BIC = ", BIC(gam.model)))
}
```


```{r fig.width=8, fig.height=5}

gam.model <- gam(alive ~ s(age, k = 6, by = factor(transplant)) + factor(transplant), data = heart, family = binomial)

tmp <- predict(gam.model, newdata = data.frame(age = age.range, transplant = rep(1, 100)), type = "link", se.fit = TRUE)
gam.transplant.prob <- plogis(tmp$fit)
gam.transplant.ub <- plogis(tmp$fit + qnorm(0.975) * tmp$se.fit)
gam.transplant.lb <- plogis(tmp$fit - qnorm(0.975) * tmp$se.fit)

tmp <- predict(gam.model, newdata = data.frame(age = age.range, transplant = rep(0, 100)), type = "link", se.fit = TRUE)
gam.notransplant.prob <- plogis(tmp$fit)
gam.notransplant.ub <- plogis(tmp$fit + qnorm(0.975) * tmp$se.fit)
gam.notransplant.lb <- plogis(tmp$fit - qnorm(0.975) * tmp$se.fit)

pdf("/Users/chenxingran/University of Michigan Dropbox/Xingran Chen/UMICH Courses/BIOSTAT 885/gam_tp.pdf", width = 8, height = 5)
par(cex = 1.1,            
    cex.axis = 1.1,       
    cex.lab = 1.1,        
    cex.main = 1.1,      
    cex.sub = 1.1)

plot(age.range, gam.transplant.prob, type = "l", xlab = "Age", 
     ylab = "Probability of Survival", ylim = c(0, 1), col = "blue", lwd = 2)
lines(age.range, gam.transplant.ub, col = "blue", lty=2, lwd=1)
lines(age.range, gam.transplant.lb, col = "blue", lty=2, lwd=1)
lines(age.range, gam.notransplant.prob, col = "red", lty=1, lwd=2)
lines(age.range, gam.notransplant.ub, col = "red", lty=2, lwd=1)
lines(age.range, gam.notransplant.lb, col = "red", lty=2, lwd=1)
legend("topright", legend=c("Transplant", "No Transplant"), col=c("blue", "red"), lty=1:2, cex=0.8)

```


```{r}
for (k in 1:20){
  gam.model <- gam(alive ~ s(age, k = k, by = factor(transplant), bs = "cr") + factor(transplant), data = heart, family = binomial)
  print(paste("k = ", k, "AIC = ", AIC(gam.model), "BIC = ", BIC(gam.model)))
}
```

```{r fig.width=8, fig.height=5}

gam.model <- gam(alive ~ s(age, k = 5, by = factor(transplant), bs = "cr") + factor(transplant), data = heart, family = binomial)

tmp <- predict(gam.model, newdata = data.frame(age = age.range, transplant = rep(1, 100)), type = "link", se.fit = TRUE)
gam.transplant.prob <- plogis(tmp$fit)
gam.transplant.ub <- plogis(tmp$fit + qnorm(0.975) * tmp$se.fit)
gam.transplant.lb <- plogis(tmp$fit - qnorm(0.975) * tmp$se.fit)

tmp <- predict(gam.model, newdata = data.frame(age = age.range, transplant = rep(0, 100)), type = "link", se.fit = TRUE)
gam.notransplant.prob <- plogis(tmp$fit)
gam.notransplant.ub <- plogis(tmp$fit + qnorm(0.975) * tmp$se.fit)
gam.notransplant.lb <- plogis(tmp$fit - qnorm(0.975) * tmp$se.fit)

pdf("/Users/chenxingran/University of Michigan Dropbox/Xingran Chen/UMICH Courses/BIOSTAT 885/gam_cr.pdf", width = 8, height = 5)
par(cex = 1.1,            
    cex.axis = 1.1,       
    cex.lab = 1.1,        
    cex.main = 1.1,      
    cex.sub = 1.1)

plot(age.range, gam.transplant.prob, type = "l", xlab = "Age", 
     ylab = "Probability of Survival", ylim = c(0, 1), col = "blue", lwd = 2)

lines(age.range, gam.transplant.ub, col = "blue", lty=2, lwd=1)
lines(age.range, gam.transplant.lb, col = "blue", lty=2, lwd=1)
lines(age.range, gam.notransplant.prob, col = "red", lty=1, lwd=2)
lines(age.range, gam.notransplant.ub, col = "red", lty=2, lwd=1)
lines(age.range, gam.notransplant.lb, col = "red", lty=2, lwd=1)
legend("topright", legend=c("Transplant", "No Transplant"), col=c("blue", "red"), lty=1:2, cex=0.8)

```